version: '3.8'

services:
  prometheus:
    image: prom/prometheus:v2.28.0
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus

  prometheus-exporter:
    image: prom/snmp-exporter:v0.20.0
    ports:
      - "9116:9116"
    volumes:
      - ./snmp.yml:/etc/snmp_exporter/snmp.yml
  
  speedtest-exporter:
    image: billimek/prometheus-speedtest-exporter:1.1.0
    ports:
      - "9469:9469"

  grafana:
    image: grafana/grafana:8.0.3
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
      - ./custom.ini:/etc/grafana/grafana.ini

volumes:
  grafana-data:
  prometheus-data:
