global:
  scrape_interval:     15s
  evaluation_interval: 15s
  scrape_timeout:      10s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
    - targets: ['192.168.0.10:9090']
  - job_name: 'speedtest'
    static_configs:
      - targets:
        - 192.168.0.10:9469
    metrics_path: /probe
    params:
      script: [speedtest]
    scrape_interval: 60m
    scrape_timeout: 10m
  - job_name: 'snmp'
    static_configs:
      - targets:
        - 192.168.0.100
    metrics_path: /snmp
    params:
      module: [if_mib]
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 192.168.0.10:9116
    scrape_interval: 3m
    scrape_timeout: 60s
